### ISSUE TITLE
Request: do not backup/restore if creating a new interfaces file

### ISSUE THREAD

**Issue by mchubby** [nMustaki/debinterface#13]
Hello,
`InterfacesWriter._backup_interfaces()` raises an `IOError` if the source interfaces file does not exist beforehand. (call to `shutil.copy`)

My use case is specifying a non-default `interfaces_path` in the `Interfaces` constructor, along with `update_adapters=False`

I think it would be best if it is not mandatory to have an existing file, possibly under specific conditions/flags.

**Comment by nMustaki** [comment]
Hi,

I think a flag "no_backup" would be safer because I want an exception if
the source file does not exist, what do you think ?

Do you want to submit a PR, or do you want me to do it ?


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Comment by mchubby** [comment]
OK, I'll leave it to you :)

**Comment by nMustaki** [comment]
Hoping it's not too late... I settled for not raising an exception if the source file does not exist, that should cover both our feature requirements
